{% set data = load_setup_py_data() %}

package:
  name: ipywidgets_bokeh
  version: {{ data["version"] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py build_js install --single-version-externally-managed --record record.txt

extra:
  channels:
    - bokeh/label/dev
    - bokeh
    - conda-forge

requirements:
  build:
    - python >=3.9
    - setuptools
    - nodejs 18.*
  run:
    - python >=3.9
    - bokeh 3.* # TODO 3.2.dev1
    - ipywidgets 8.*
    - ipykernel 6.*,!=6.18 # until ipywidgets 8.0.6

test:
  imports:
    - ipywidgets_bokeh

about:
  home: {{ data["url"] }}
  license: {{ data["license"] }}
  summary: {{ data["description"] }}

extra:
  deploy:
    - anaconda-client
    - setuptools
    - twine
    - jq
